### ISSUE TITLE
Geocoding failing on update

### ISSUE THREAD

**Issue by seancdavis** [seancdavis/sapwood#16]
```
Caught an error during Google geocoding call: undefined method `encoding' for #<Hash:0x007faa254e0878>
```

**Comment by seancdavis** [comment]
Looks like it happened because the address was blank. Just need a simple catch for that.

**Comment by seancdavis** [comment]
This was perhaps a regression from the transition that came with #15. It may not be an issue, but will look into it.
